#! /bin/sh
# -*- mode: sh -*-
# Código Cristo
#
# Referencias aprendidas:
#
# https://man.archlinux.org/man/community/yad/yad.1.en
# https://sanana.kiev.ua/index.php/yad
# http://smokey01.com/yad/
# https://github.com/offternet/yaddemo
#

res1=$(mktemp --tmpdir term-tab1.XXXXXXXX)
res2=$(mktemp --tmpdir term-tab2.XXXXXXXX)
res3=$(mktemp --tmpdir term-tab3.XXXXXXXX)
res4=$(mktemp --tmpdir term-tab4.XXXXXXXX)
res5=$(mktemp --tmpdir term-tab5.XXXXXXXX)
res6=$(mktemp --tmpdir term-tab6.XXXXXXXX)
res7=$(mktemp --tmpdir term-tab7.XXXXXXXX)

KEY=$RANDOM


source bash/num1
export -f idioma
export -f zone
export -f keyX11


yad --plug=$KEY --tabnum=1 \
--form  --separator=" " --item-separator="," \
--text="<b>\nEvite ingresar caracteres especiales ! # $ % ( ) * +, -. / \nTendrá que volver a llenar los datos nuevamente.  Por favor ingrese sus datos:\n</b>" \
--field="<b>Usuario Nuevo</b>" "usuario" \
--field="<span color='#07BFFF'><b>Contraseña de Usuario</b></span>:H" "Clave" \
--field="<span color='#07BFFF'>Repita Contraseña</span>:H" "Clave" \
--field="<span color='#FF3333'><b>Contraseña de Root</b></span>:H" "Clave" \
--field="<span color='#FF3333'>Repita Contraseña</span>:H" "Clave" \
--field="Idioma:FBTN" 'bash -c "idioma"' \
--field="Zona Horaria:FBTN" 'bash -c "zone"' \
--field="Teclado:FBTN" 'bash -c "keyX11"' > $res1 &

source bash/num2
export -f partauto
export -f partmanual
export -f partcifrado
export -f partwindows

export -f partautoRoot
export -f partautoSwap
export -f partautoHome
export -f partautoHomeSwap


yad --plug=$KEY --tabnum=2 --align=left \
--form  --columns=2  --separator=" "  \
--text="<b>\nIngrese el tipo de particionado en el disco a instalar</b>:\n" \
--field="Particionado Automatico:FBTN" 'bash -c "partauto"' \
--field="Particionado Automatico con Cifrado:FBTN" 'bash -c "partcifrado"' \
--field="Particionado Manual:FBTN" 'bash -c "partmanual"' \
--field="Particionado con otro Sistema Operativo:FBTN" 'bash -c "partwindows"' > $res2 &


kernels=$(echo "linux,linux-hardened,linux-lts,linux-zen")
shells=$(echo "zsh,bash,dash,fish,mksh,tcsh")

yad --plug=$KEY --tabnum=3 --align=left \
--form  --separator=" " --item-separator=","   \
--text="<b>\nSelecciona el Kernel para tu sistema y algunos extras:</b>\n" \
--field="Kernel del Sistema:CB" "${kernels}" \
--field="Shell del Sistema:CB" "${shells}" \
--field="Selecciona los modulos que necesitas:LBL" \
--field="Microcode del Procesador (Actualizaciones):CHK" \
--field="Driver para Touchpad - Panel táctil (Laptop):CHK" \
--field="<span color='white'><b>\n\t\t\t\tApóyame en Patreon: https://www.patreon.com/codigocristo</b></span>:LBL" > $res3 &


source bash/num4
export -f deorwm
export -f desktop
export -f winmanager

yad --plug=$KEY --tabnum=4 --align=left \
--form --separator=" " --item-separator="," --image="patreon.png" --image-on-top \
--text="<span color='white'><b>\n\n\tApóyame en Patreon: https://www.patreon.com/codigocristo\n</b></span>" \
--field="Elige entre un DE o WM o TTY :FBTN" 'bash -c "deorwm"' \
--field="<span color='white'><b>\nDesktop Environment (DE)</b></span>\nUn entorno de escritorio proporciona una completa interfaz gráfica de usuario:LBL" \
--field="<span color='white'><b>\nWindow Manager (WM)</b></span>\nUn gestor de ventanas proporciona al usuario una interfaz gráfica minimalista:LBL" \
--field="<span color='white'><b>\nGetty (TTY)</b></span>\nUna consola getty es el nombre genérico que gestiona una línea de terminal:LBL" > $res4 &



drivideo=$(echo "Automático,Video vesa (Generic All),Intel (Open Source),AMD - ATI (Open Source),AMD - Radeon (Open Source),Nvidia (Open Source),Nvidia 440xx (Linux Stable),Nvidia 390xx (Linux Stable),Nvidia 440xx (Linux LTS),Nvidia 390xx (Linux LTS),Nvidia 440xx (Linux Hardened - Zen),Nvidia 390xx (Linux Hardened - Zen),Nvidia 440xx (Linux Stable + Intel)")
driaudio=$(echo "Pulse Audio,Alsa Audio,Jack Audio,Pipewire Audio")
driaur=$(echo "Ninguno,yay (Terminal),paru (Terminal),pamac (Graphical),Octopi (Graphical)")
webs=$(echo "Ninguno,Firefox,Chromium,Brave,Google Chrome,Opera,Vivaldi")
driofi=$(echo "Ninguno,LibreOffice,WPS Office,SoftMaker Office")
driwifi=$(echo "Ninguno,Automatico,Broadcom 802.11 Linux Stable,Broadcom 802.11 Others Kernels")
driblue=$(echo "Ninguno,bluetoothctl (Terminal),blueman(Graphical)")

yad --plug=$KEY --tabnum=5 --align=left \
--form  --separator=" " --item-separator=","   \
--field="Driver de Vídeo:CB" "${drivideo}" \
--field="Sistema de Audio:CB" "${driaudio}" \
--field="AUR Helper:CB" "${driaur}" \
--field="Navegador Web:CB" "${webs}" \
--field="Ofimática:CB" "${driofi}" \
--field="Wifi:CB" "${driwifi}" \
--field="Bluetooth:CB" "${driblue}" > $res5 &



yad --plug=$KEY --tabnum=6 --align=left \
--form  --columns=2  --separator=" " --item-separator=","   \
--text="\nAgrega tus programas favoritos para tu sistema Arch:\n" \
--field="Lectura y formateo de discos incluido Android:CHK" \
--field="Compresión y Descompresión de archivos:CHK" \
--field="Códecs de video - lectura de todos los formatos:CHK" \
--field="gufw - Firewall de red:CHK" \
--field="hardinfo - Información del sistema y benchmark:CHK" \
--field="gparted - Administrador de Discos:CHK" \
--field="viewnior - Visor de Imagenes:CHK" \
--field="vlc - Reproductor de Video:CHK" \
--field="audacious - Reproductor de Audio:CHK" \
--field="spotify - Sin Anuncios adblock:CHK" \
--field="gnome-system-monitor - Admin de Procesos:CHK" \
--field="htop - Administrador de Procesos:CHK" \
--field="Telegram - telegram-desktop:CHK" \
--field="Steam - Wine + Proton:CHK" \
--field="Lutris - Plataforma de juegos Open Source:CHK" \
--field="OBS-Studio - Software de código abierto:CHK" > $res6 &


inxi -CDGNm -y 90 | yad --image="cpu"  --plug=$KEY --tabnum=7 --align="left" \
--text-info --text="\nInformación del Sistema\n" > $res7 &


yad --center --window-icon="cuadroicon.png" --image="unnamed.jpg" --image-on-top --title="Instalador Arcris" \
--geometry=600x500  --text="\t\t\t\t  <span size='large' color='#07BFFF'><b>>_  Instalar Arch Linux - ArcriS</b></span>" --borders="10" \
--button="  Cancelar!gtk-no:0" --button="  Instalar!gtk-ok:0"  --notebook --key=$KEY --tab="Información" --tab="Disco" --tab="Kernel" --tab="DE o WM" --tab="Programas" --tab="Extras" --tab="Detalles del Sistema"

if [ $? = "0" ] 
  	then killall yad
fi



clear 
cat $res1 > datosuser
cat $res2 >> datosuser
cat $res3 >> datosuser
cat $res4 >> datosuser 
cat $res5 >> datosuser
cat $res6 >> datosuser


numerodelineas=$(cat datosuser | wc -l)

username=$(cat datosuser | awk 'NR>=1&&NR<=1' |  awk '{print $1}')

echo $username

if printf "%s" "$username" | grep -Eoq "^[a-z][a-z0-9-]*$" && [ "${#username}" -lt 33 ]; then
	#zenity --warning --width="250" --height="50"  --text "\nUSUARIO BIEN\n"
	if grep -Fxq "$username" reserved_usernames ; then
	zenity --error --width="350" --height="50"  --text "\nNOMBRE DE USUARIO RESERVADO PARA EL SISTEMA\n"
	fi
else
	zenity --error --width="450" --height="100"  --text "\nNOMBRE DE USUARIO CONTIENE CARACTERES ESPECIALES\nVUELVE A LLENAR LOS CAMPOS DEL INSTALADOR\n"
fi







#sudo pacman -Sy --noconfirm  | yad --geometry=400x500 --text-info --tail  --text="\nInstalando\n"


#sudo pacman -Sy | yad --geometry=400x500 --listen --list --separator="" \
#--column="GRUB Menu Entry"