#!/bin/bash


function mensaje_install {
echo ""
echo "          █████╗ ██████╗  ██████╗██████╗ ██╗███████╗";
echo "         ██╔══██╗██╔══██╗██╔════╝██╔══██╗██║██╔════╝";
echo "         ███████║██████╔╝██║     ██████╔╝██║███████╗";
echo "         ██╔══██║██╔══██╗██║     ██╔══██╗██║╚════██║";
echo "         ██║  ██║██║  ██║╚██████╗██║  ██║██║███████║";
echo "         ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚══════╝";
echo "                                                    ";
}







echo ""
echo -e '                             -`                  '
echo -e '                           .o+`                  '
echo -e '                           `ooo/                   '
echo -e '                          `+oooo:                 '
echo -e '                         `+oooooo:                 ' 
echo -e '                         -+oooooo+:                '
echo -e '                       `/:-:++oooo+:              '
echo -e '                      `/++++/+++++++:              '
echo -e '                     `/++++++++++++++:             '
echo -e '                    `/+++ooooooooooooo/`           '
echo -e '                   ./ooosssso++osssssso+`          '
echo -e '                  .oossssso-````/ossssss+`         '
echo -e '                 -osssssso.      :ssssssso.        '
echo -e '                :osssssss/        osssso+++.       '
echo -e '               /ossssssss/        +ssssooo/-       '
echo -e '             `/ossssso+/:-        -:/+osssso+-     '
echo -e '            `+sso+:-`                 `.-/+oso:    '
echo -e '           `++:.                           `-/+/   '
echo -e '           .`                                 `/   '
echo ""
echo -e "         Visita el Canal de Youtube de Código Cristo"
sleep 5


######## VARIABLES #############################################################
kernel_select=$(cat datosuser | awk 'NR>=7&&NR<=7' |  awk '{print $1}')
         disk=$(cat datosuser | awk 'NR>=5&&NR<=5' |  awk '{print $1}')
     username=$(cat datosuser | awk 'NR>=4&&NR<=4' |  awk '{print $1}')
      keymapx=$(cat datosuser | awk 'NR>=3&&NR<=3' |  awk '{print $1}')
  zonahoraria=$(cat datosuser | awk 'NR>=2&&NR<=2' |  awk '{print $1}')
   localefrom=$(cat datosuser | awk 'NR>=1&&NR<=1' |  awk '{print $1}') 
        video=$(cat datosuser | awk 'NR>=10&&NR<=10' |  awk '{print $1}')
  environment=$(cat datosuser | awk 'NR>=8&&NR<=8' |  awk '{print $1}')
################################################################################


echo -e ""
echo -e "\t\t\t| Zona Horaria en LiveCD |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
echo ""
timedatectl set-timezone ${zonahoraria}
hwclock -w
hwclock --hctosys
hwclock --systohc
ntpd -qg
echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando Hora Actual en LiveCD |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 2
timedatectl status
echo ""
date +' %A, %B %d, %Y - %r'
sleep 5
echo "" 
echo "" 


echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando lista de Keys en LiveCD |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 2
pacman -Sy archlinux-keyring --noconfirm 
sleep 2
echo "" 
echo "" 


echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando MirrorList en LiveCD |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 3
pacman -Sy reflector --noconfirm 
pacman -Sy python3 --noconfirm 
pacman -Sy rsync --noconfirm 

echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando mejores listas de Mirrors |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 3
reflector --verbose --latest 6 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
sleep 3
echo "" 
echo "" 
cat /etc/pacman.d/mirrorlist
sleep 3
echo "" 
echo "" 


echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Instalando: Base y Base-devel |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 3
pacstrap /mnt base
pacstrap /mnt base-devel
pacstrap /mnt reflector python3 rsync
pacstrap /mnt nano 
pacstrap /mnt xdg-user-dirs


echo "" 
echo "" 
echo -e ""
echo -e "\t| Actualizando mejores listas de Mirrors del sistema instalado |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
arch-chroot /mnt /bin/bash -c "reflector --verbose --latest 6 --protocol https --sort rate --save /etc/pacman.d/mirrorlist"
cat /mnt/etc/pacman.d/mirrorlist
sleep 3
echo ""
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"


echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Agregando Repositorio de Arcris |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
cp pacmancristo.conf /mnt/etc/pacman.conf
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"


echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Archivo FSTAB |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
genfstab -U /mnt > /mnt/etc/fstab
echo ""
arch-chroot /mnt /bin/bash -c "cat /etc/fstab"
sleep 3



hostname=Arcris
username=$(cat datosuser | awk 'NR>=4&&NR<=4' |  awk '{print $1}')
userpasswd=$(cat datosuser | awk 'NR>=4&&NR<=4' |  awk '{print $2}')
rootpasswd=$(cat datosuser | awk 'NR>=4&&NR<=4' |  awk '{print $4}')
keymap=$( curl https://ipapi.co/languages | awk -F "," '{print $1}' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' )

echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Usuario y Administrador |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
echo "${hostname}" > /mnt/etc/hostname
echo "127.0.1.1 ${hostname}.localdomain ${hostname}" > /mnt/etc/hosts
echo ""
echo "Hostname: $(cat /mnt/etc/hostname)"
echo ""
echo "Hosts: $(cat /mnt/etc/hosts)"
echo ""
sleep 5
arch-chroot /mnt /bin/bash -c "(echo ${rootpasswd} ; echo ${rootpasswd}) | passwd root"
arch-chroot /mnt /bin/bash -c "useradd -m -g users -s /bin/bash ${username}"
arch-chroot /mnt /bin/bash -c "(echo ${userpasswd} ; echo ${userpasswd}) | passwd ${username}"
sed -i "80i ${username} ALL=(ALL) NOPASSWD: ALL"  /mnt/etc/sudoers


echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando Idioma del Sistema |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
echo "${localefrom} UTF-8" > /mnt/etc/locale.gen
arch-chroot /mnt /bin/bash -c "locale-gen" 
echo ""
echo "LANG=$localefrom" > /mnt/etc/locale.conf && cat /mnt/etc/locale.conf 
echo "KEYMAP=$keymap" > /mnt/etc/vconsole.conf && cat /mnt/etc/vconsole.conf 
echo ""
arch-chroot /mnt /bin/bash -c "export $(cat /mnt/etc/locale.conf)" 
export $(cat /mnt/etc/locale.conf)
arch-chroot /mnt /bin/bash -c "sudo -u $username export $(cat /etc/locale.conf)"
export $(cat /mnt/etc/locale.conf)
sleep 5


echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando lista de Directoros |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
arch-chroot /mnt /bin/bash -c "xdg-user-dirs-update"
arch-chroot /mnt /bin/bash -c "sudo -u $username xdg-user-dirs-update"
echo ""
arch-chroot /mnt /bin/bash -c "ls -l /root/"
echo ""
echo ""
arch-chroot /mnt /bin/bash -c "ls -l /home/$username/"
echo ""
sleep 5



echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando Zona Horaria |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
ln -sf /usr/share/zoneinfo/${zonahoraria} /mnt/etc/localtime
arch-chroot /mnt /bin/bash -c "timedatectl set-timezone ${zonahoraria}"
arch-chroot /mnt /bin/bash -c "hwclock -w"
arch-chroot /mnt /bin/bash -c "hwclock --hctosys"
arch-chroot /mnt /bin/bash -c "hwclock --systohc"
sleep 2
arch-chroot /mnt /bin/bash -c "timedatectl status"
echo ""
arch-chroot /mnt /bin/bash -c "date +' %A, %B %d, %Y - %I:%M %p'"
sleep 5



kernel_select=$(cat datosuser | awk 'NR>=7&&NR<=7' |  awk '{print $1}')
shell_select=$(cat datosuser | awk 'NR>=7&&NR<=7' |  awk '{print $2}')
ucode_select=$(cat datosuser | awk 'NR>=7&&NR<=7' |  awk '{print $3}')
touchpad_select=$(cat datosuser | awk 'NR>=7&&NR<=7' |  awk '{print $4}')

source bash/installkernel
echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Instalando Kernel Seleccionado |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
installkernel
echo -e ""
echo -e "\t\t\t| Instalando Shell del Sistema |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
installshell
echo -e ""
installucode
echo -e ""
installtouchpad


video=$(cat datosuser | awk 'NR>=10&&NR<=10' |  awk '{print $1}')
echo -e ""
echo -e "\t\t\t| Instalando Shell del Sistema |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
installvideo


environment=$(cat datosuser | awk 'NR>=8&&NR<=8' |  awk '{print $1}')
echo -e ""
echo -e "\t\t\t| Instalando Shell del Sistema |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
installenvironment



source bash/installgrub
echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Instalando GRUB |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
installgrub



echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Quitando Repositorio de Arcris |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
cp pacman.conf /mnt/etc/pacman.conf
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
echo ""
echo ""
arch-chroot /mnt /bin/bash -c "sudo -u $username alsi -l"
echo ""
arch-chroot /mnt /bin/bash -c "systemctl enable dhcpcd NetworkManager"
echo ""
arch-chroot /mnt /bin/bash -c "systemctl start dhcpcd NetworkManager"
echo ""
echo "noipv6rs" >> /mnt/etc/dhcpcd.conf
echo "noipv6" >> /mnt/etc/dhcpcd.conf
echo ""
sed -i '80d' /mnt/etc/sudoers
sed -i "80i ${username} ALL=(ALL) ALL" /mnt/etc/sudoers



echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo -e '                             -`                  '
echo -e '                           .o+`                  '
echo -e '                           `ooo/                   '
echo -e '                          `+oooo:                 '
echo -e '                         `+oooooo:                 ' 
echo -e '                         -+oooooo+:                '
echo -e '                       `/:-:++oooo+:              '
echo -e '                      `/++++/+++++++:              '
echo -e '                     `/++++++++++++++:             '
echo -e '                    `/+++ooooooooooooo/`           '
echo -e '                   ./ooosssso++osssssso+`          '
echo -e '                  .oossssso-````/ossssss+`         '
echo -e '                 -osssssso.      :ssssssso.        '
echo -e '                :osssssss/        osssso+++.       '
echo -e '               /ossssssss/        +ssssooo/-       '
echo -e '             `/ossssso+/:-        -:/+osssso+-     '
echo -e '            `+sso+:-`                 `.-/+oso:    '
echo -e '           `++:.                           `-/+/   '
echo -e '           .`                                 `/   '
echo ""
echo -e "       Instalación Completa - Reinicia tu Computadora     " 
echo ""
mensaje_install

sleep 5