#!/bin/bash


function mensaje_install {
echo ""
echo "          █████╗ ██████╗  ██████╗██████╗ ██╗███████╗";
echo "         ██╔══██╗██╔══██╗██╔════╝██╔══██╗██║██╔════╝";
echo "         ███████║██████╔╝██║     ██████╔╝██║███████╗";
echo "         ██╔══██║██╔══██╗██║     ██╔══██╗██║╚════██║";
echo "         ██║  ██║██║  ██║╚██████╗██║  ██║██║███████║";
echo "         ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚══════╝";
echo "                                                    ";
}







echo ""
echo -e '                             -`                  '
echo -e '                           .o+`                  '
echo -e '                           `ooo/                   '
echo -e '                          `+oooo:                 '
echo -e '                         `+oooooo:                 ' 
echo -e '                         -+oooooo+:                '
echo -e '                       `/:-:++oooo+:              '
echo -e '                      `/++++/+++++++:              '
echo -e '                     `/++++++++++++++:             '
echo -e '                    `/+++ooooooooooooo/`           '
echo -e '                   ./ooosssso++osssssso+`          '
echo -e '                  .oossssso-````/ossssss+`         '
echo -e '                 -osssssso.      :ssssssso.        '
echo -e '                :osssssss/        osssso+++.       '
echo -e '               /ossssssss/        +ssssooo/-       '
echo -e '             `/ossssso+/:-        -:/+osssso+-     '
echo -e '            `+sso+:-`                 `.-/+oso:    '
echo -e '           `++:.                           `-/+/   '
echo -e '           .`                                 `/   '
echo ""
echo -e "         Visita el Canal de Youtube de Código Cristo"
sleep 5


kernel_select=$(cat datosuser | awk 'NR>=7&&NR<=7' |  awk '{print $1}')
         disk=$(cat datosuser | awk 'NR>=5&&NR<=5' |  awk '{print $1}')
      keymapx=$(cat datosuser | awk 'NR>=3&&NR<=3' |  awk '{print $1}')
  zonahoraria=$(cat datosuser | awk 'NR>=2&&NR<=2' |  awk '{print $1}')
   localefrom=$(cat datosuser | awk 'NR>=1&&NR<=1' |  awk '{print $1 " " $2}') 
        video=$(cat datosuser | awk 'NR>=10&&NR<=10' |  awk '{print $1}')
  environment=$(cat datosuser | awk 'NR>=8&&NR<=8' |  awk '{print $1}')


echo -e ""
echo -e "\t\t\t| Zona Horaria en LiveCD |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
echo ""
timedatectl set-timezone ${zonahoraria}
hwclock -w
hwclock --hctosys
hwclock --systohc
ntpd -qg
echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando Hora Actual en LiveCD |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 2
timedatectl status
echo ""
date +' %A, %B %d, %Y - %r'
sleep 5
echo "" 
echo "" 


echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando lista de Keys en LiveCD |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 2
pacman -Sy archlinux-keyring --noconfirm 
sleep 2
echo "" 
echo "" 


echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando MirrorList en LiveCD |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 3
pacman -Sy reflector --noconfirm 
pacman -Sy python3 --noconfirm 
pacman -Sy rsync --noconfirm 

echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| Actualizando mejores listas de Mirrors |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
sleep 3
reflector --verbose --latest 6 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
sleep 3
echo "" 
echo "" 
cat /etc/pacman.d/mirrorlist
sleep 3
echo "" 
echo "" 







echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo -e '                             -`                  '
echo -e '                           .o+`                  '
echo -e '                           `ooo/                   '
echo -e '                          `+oooo:                 '
echo -e '                         `+oooooo:                 ' 
echo -e '                         -+oooooo+:                '
echo -e '                       `/:-:++oooo+:              '
echo -e '                      `/++++/+++++++:              '
echo -e '                     `/++++++++++++++:             '
echo -e '                    `/+++ooooooooooooo/`           '
echo -e '                   ./ooosssso++osssssso+`          '
echo -e '                  .oossssso-````/ossssss+`         '
echo -e '                 -osssssso.      :ssssssso.        '
echo -e '                :osssssss/        osssso+++.       '
echo -e '               /ossssssss/        +ssssooo/-       '
echo -e '             `/ossssso+/:-        -:/+osssso+-     '
echo -e '            `+sso+:-`                 `.-/+oso:    '
echo -e '           `++:.                           `-/+/   '
echo -e '           .`                                 `/   '
echo ""
echo -e "       Instalación Completa - Reinicia tu Computadora     " 
echo ""
mensaje_install

sleep 5