#! /bin/sh
# -*- mode: sh -*-
# Código Cristo
#
# Referencias aprendidas:
#
# https://man.archlinux.org/man/community/yad/yad.1.en
# https://sanana.kiev.ua/index.php/yad
# http://smokey01.com/yad/
# https://github.com/offternet/yaddemo
# http://rpm.pbone.net/manpage_idpl_17003956_numer_1_nazwa_yad.html
#

rm datosuser

res1=$(mktemp --tmpdir term-tab1.XXXXXXXX)
res2=$(mktemp --tmpdir term-tab2.XXXXXXXX)
res3=$(mktemp --tmpdir term-tab3.XXXXXXXX)
res4=$(mktemp --tmpdir term-tab4.XXXXXXXX)
res5=$(mktemp --tmpdir term-tab5.XXXXXXXX)
res6=$(mktemp --tmpdir term-tab6.XXXXXXXX)
res7=$(mktemp --tmpdir term-tab7.XXXXXXXX)

KEY=$RANDOM


source bash/num1
export -f idioma
export -f zone
export -f keyX11


yad --plug=$KEY --tabnum=1 \
--form  --separator=" " --item-separator="," \
--text="<b>\nEvite ingresar caracteres especiales ! # $ % ( ) * +, -. / \nTendrá que volver a llenar todos los campos nuevamente.  Por favor ingrese sus datos:\n</b>" \
--field="<b>Usuario Nuevo</b>" "usuario" \
--field="<span color='#07BFFF'><b>Contraseña de Usuario</b></span>:H" "Clave" \
--field="<span color='#07BFFF'>Repita Contraseña</span>:H" "Clave" \
--field="<span color='#FF3333'><b>Contraseña de Root</b></span>:H" "Clave" \
--field="<span color='#FF3333'>Repita Contraseña</span>:H" "Clave" \
--field="Idioma:FBTN" 'bash -c "idioma"' \
--field="Zona Horaria:FBTN" 'bash -c "zone"' \
--field="Teclado:FBTN" 'bash -c "keyX11"' > $res1 &

source bash/num2
export -f partauto
export -f partmanual
export -f partcifrado
export -f partwindows

export -f partautoRoot
export -f partautoSwap
export -f partautoHome
export -f partautoHomeSwap


yad --plug=$KEY --tabnum=2 --align=left \
--form  --columns=2  --separator=" "  \
--text="<b>\nIngrese el tipo de particionado en el disco a instalar</b>:\n" \
--field="Particionado Automatico:FBTN" 'bash -c "partauto"' \
--field="Particionado Automatico con Cifrado:FBTN" 'bash -c "partcifrado"' \
--field="Particionado Manual:FBTN" 'bash -c "partmanual"' \
--field="Particionado con otro Sistema Operativo:FBTN" 'bash -c "partwindows"' > $res2 &


kernels=$(echo "linux-stable,linux-hardened,linux-lts,linux-zen")
shells=$(echo "zsh,bash,dash,fish,mksh,tcsh")

yad --plug=$KEY --tabnum=3 --align=left --print-uri \
--form  --separator=" " --item-separator=","   \
--text="<b>\nSelecciona el Kernel para tu sistema y algunos extras:</b>\n" \
--field="Kernel del Sistema:CB" "${kernels}" \
--field="Shell del Sistema:CB" "${shells}" \
--field="Selecciona los modulos que necesitas:LBL" \
--field="Microcode del Procesador (Actualizaciones):CHK" \
--field="Driver para Touchpad - Panel táctil (Laptop):CHK" \
--field="<span color='white'><b>\n\t\t\t\t\tApóyame en Patreon: </b></span><span color='#07BFFF'><b>patreon.com/codigocristo</b></span>:LBL" > $res3 &


source bash/num4
export -f deorwm
export -f desktop
export -f winmanager

yad --plug=$KEY --tabnum=4 --align=left \
--form --separator=" " --item-separator=","  \
--text="<span color='white'><b>\n\n\t\t\t\t\t\tDonaciones en: </b></span><span color='#07BFFF'><b>paypal.me/codigocristo\n</b></span>" \
--field="Elige entre un DE o WM o TTY :FBTN" 'bash -c "deorwm"' \
--field="<span color='white'><b>\nDesktop Environment (DE)</b></span>\nUn entorno de escritorio proporciona una completa interfaz gráfica de usuario:LBL" \
--field="<span color='white'><b>\nWindow Manager (WM)</b></span>\nUn gestor de ventanas proporciona al usuario una interfaz gráfica minimalista:LBL" \
--field="<span color='white'><b>\nGetty (TTY)</b></span>\nUna consola getty es el nombre genérico que gestiona una línea de terminal:LBL" > $res4 &



drivideo=$(echo "Automático,Video_vesa_(Generic_All),Intel_(Open_Source),AMD/ATI_(Open_Source),AMD/Radeon_(Open_Source),Nvidia_(Open_Source),Nvidia_Privativo_440xx_(Linux_Stable),Nvidia_Privativo_390xx_(Linux_Stable),Nvidia_Privativo_440xx_(Linux_LTS),Nvidia_Privativo_390xx_(Linux_LTS),Nvidia_Privativo_440xx_(Linux_Hardened_-_Zen),Nvidia_Privativo_390xx_(Linux_Hardened_-_Zen),Nvidia_Privativo_440xx_(Linux_Stable_+_Intel)")
driaudio=$(echo "Pulse-Audio,Alsa-Audio,Jack-Audio,Pipewire-Audio")
driaur=$(echo "yay-(Terminal),paru-(Terminal),pamac-(Graphical),Octopi-(Graphical),Ninguno")
webs=$(echo "Ninguno,Firefox,Chromium,Brave,Google-Chrome,Opera,Vivaldi")
driofi=$(echo "Ninguno,LibreOffice,WPS-Office,SoftMaker-Office")
driwifi=$(echo "Ninguno,Automático,Broadcom-802.11-Linux-Stable,Broadcom-802.11-Others-Kernels")
driblue=$(echo "Ninguno,bluetoothctl-(Terminal),blueman-(Graphical)")

yad --plug=$KEY --tabnum=5 --align=left \
--form  --separator=" " --item-separator=","   \
--field="Driver de Vídeo:CB" "${drivideo}" \
--field="Sistema de Audio:CB" "${driaudio}" \
--field="AUR Helper:CB" "${driaur}" \
--field="Navegador Web:CB" "${webs}" \
--field="Ofimática:CB" "${driofi}" \
--field="Wifi:CB" "${driwifi}" \
--field="Bluetooth:CB" "${driblue}" > $res5 &



yad --plug=$KEY --tabnum=6 --align=left \
--form  --columns=2  --separator=" " --item-separator=","   \
--text="\nAgrega tus programas favoritos para tu sistema Arch:\n" \
--field="Lectura y formateo de discos incluido Android:CHK" \
--field="Compresión y Descompresión de archivos:CHK" \
--field="Códecs de video - lectura de todos los formatos:CHK" \
--field="gufw - Firewall de red:CHK" \
--field="hardinfo - Información del sistema y benchmark:CHK" \
--field="gparted - Administrador de Discos:CHK" \
--field="viewnior - Visor de Imagenes:CHK" \
--field="vlc - Reproductor de Video:CHK" \
--field="audacious - Reproductor de Audio:CHK" \
--field="spotify - Sin Anuncios adblock:CHK" \
--field="gnome-system-monitor - Admin de Procesos:CHK" \
--field="htop - Administrador de Procesos:CHK" \
--field="Telegram - telegram-desktop:CHK" \
--field="Steam - Wine + Proton:CHK" \
--field="Lutris - Plataforma de juegos Open Source:CHK" \
--field="OBS-Studio - Software de código abierto:CHK" > $res6 &


inxi -CDGNm -y 90 | yad --image="cpu"  --plug=$KEY --tabnum=7 --align="left" \
--text-info --text="\nInformación del Sistema\n" > $res7 &


yad --center --window-icon="cuadroicon.png" --image="unnamed.jpg" --image-on-top --title="Instalador Arcris" \
--geometry=600x500  --text="\t\t\t\t  <span size='large' color='#07BFFF'><b>>_  Instalar Arch Linux - ArcriS</b></span>" --borders="10" \
--button="  Cancelar!gtk-no:1" --button="  Confirmar!gtk-ok:0"  --notebook --key=$KEY --tab="Información" --tab="Disco" --tab="Kernel" --tab="DE o WM" --tab="Programas" --tab="Extras" --tab="Detalles del Sistema"

if [ $? = "1" ] 
  	then killall yad
fi



clear 
cat $res1 > datosuser
cat $res2 >> datosuser
cat $res3 >> datosuser
cat $res4 >> datosuser 
cat $res5 >> datosuser
cat $res6 >> datosuser




##### CONFIRMANDO DATOS ####################################


numerodelineas=$(cat datosuser | wc -l)

username=$(cat datosuser | awk 'NR>=4&&NR<=4' |  awk '{print $1}')


if [[ $numerodelineas != 11 ]]; then
	zenity --warning --width="250" --height="50"  --text "\nInformación incompleta\n"
	sh install
else 
	if printf "%s" "$username" | grep -Eoq "^[a-z][a-z0-9-]*$" && [ "${#username}" -lt 30 ]; then
		  echo $username
		inputs_match_user=false
          while ! $inputs_match_user; do

            input=$(cat datosuser | awk 'NR>=4&&NR<=4' |  awk '{print $2}')
            confirm_input=$(cat datosuser | awk 'NR>=4&&NR<=4' |  awk '{print $3}')

            if [ -z "$input" ]; then

              zenity --error --width="350" --height="50"  --text "\nNo se le permite tener una contraseña vacía.\n"
            	sh install

            elif [ "$input" != "$confirm_input" ]; then
              
              zenity --error --width="400" --height="50"  --text "\nLas dos contraseñas de usuario que ha introducido no coinciden.\n"
              	sh install

            else
              userpasswd="$input"
              inputs_match_user=true
            fi
          done
          

        inputs_match_root=false
		  while ! $inputs_match_root; do

		    input=$(cat datosuser | awk 'NR>=4&&NR<=4' |  awk '{print $4}')
            confirm_input=$(cat datosuser | awk 'NR>=4&&NR<=4' |  awk '{print $5}')   

		    if [ -z "$input" ]; then
		      
		      zenity --error --width="350" --height="50"  --text "\nNo se le permite tener una contraseña vacía.\n"
		      	sh install

		    elif [ "$input" != "$confirm_input" ]; then

		      zenity --error --width="400" --height="50"  --text "\nLas dos contraseñas de usuario que ha introducido no coinciden.\n"
		    	sh install

		    else
		      rootpasswd="$input"
		      inputs_match_root=true
		    fi
		  done
		  
	#zenity --warning --width="250" --height="50"  --text "\nUSUARIO BIEN\n"
	if grep -Fxq "$username" reserved_usernames ; then
	zenity --error --width="350" --height="50"  --text "\nNOMBRE DE USUARIO RESERVADO PARA EL SISTEMA\n"
		sh install
	fi
	else

		zenity --error --width="450" --height="100"  --text "\nNOMBRE DE USUARIO CONTIENE CARACTERES ESPECIALES\nVUELVE A LLENAR LOS CAMPOS DEL INSTALADOR\n"
		sh install

	fi
fi

######################################################################



logoline1='                             -`                        '
logoline2='                           .o+`                        '
logoline3='                           `ooo/                       '
logoline4='                          `+oooo:                      '
logoline5='                         `+oooooo:                     ' 
logoline6='                         -+oooooo+:                    '
logoline7='                       `/:-:++oooo+:                   '
logoline8='                      `/++++/+++++++:                  '
logoline9='                     `/++++++++++++++:                 '
logoline11='                    `/+++ooooooooooooo/`               '
logoline12='                   ./ooosssso++osssssso+`              '
logoline13='                  .oossssso-````/ossssss+`             '
logoline14='                 -osssssso.      :ssssssso.            '
logoline15='                :osssssss/        osssso+++.           '
logoline16='               /ossssssss/        +ssssooo/-           '
logoline17='             `/ossssso+/:-        -:/+osssso+-         '
logoline18='            `+sso+:-`                 `.-/+oso:        '
logoline19='           `++:.                           `-/+/       '
logoline20='           .`                                 `/       '
logoline21="                          _                  _         "
logoline22="  .--.                   / \   _ __ ___ _ __(_)___     "
logoline23=" / _.-' .-.  .-.  .-.   / _ \ | '__/ __| '__| / __|    "
logoline24=" \  '-. '-'  '-'  '-'  / ___ \| | | (__| |  | \__ \    "
logoline25="  '--'                /_/   \_\_|  \___|_|  |_|___/    "


kernel_select=$(cat datosuser | awk 'NR>=7&&NR<=7' |  awk '{print $1}')
disk=$(cat datosuser | awk 'NR>=5&&NR<=5' |  awk '{print $1}')
keymapx=$(cat datosuser | awk 'NR>=3&&NR<=3' |  awk '{print $1}')
zonahoraria=$(cat datosuser | awk 'NR>=2&&NR<=2' |  awk '{print $1}')
localefrom=$(cat datosuser | awk 'NR>=1&&NR<=1' |  awk '{print $1}')
video=$(cat datosuser | awk 'NR>=10&&NR<=10' |  awk '{print $1}')
environment=$(cat datosuser | awk 'NR>=8&&NR<=8' |  awk '{print $1}')


echo -e "${logoline1}" > final
echo -e "${logoline2}" >> final
echo -e "${logoline3} Kernel  : ${kernel_select}" >> final
echo -e "${logoline4}" >> final
echo -e "${logoline5} Disco   : ${disk}" >> final
echo -e "${logoline6}" >> final
echo -e "${logoline7} Usuario : ${username}" >> final
echo -e "${logoline8}" >> final
echo -e "${logoline9} Idioma  : ${keymapx}" >> final
echo -e "${logoline11}" >> final
echo -e "${logoline12} Zona Horaria : ${zonahoraria}" >> final
echo -e "${logoline13}" >> final
echo -e "${logoline14} Ubicación : ${localefrom}" >> final
echo -e "${logoline15}" >> final
echo -e "${logoline16} Driver de Vídeo : ${video}" >> final
echo -e "${logoline17}" >> final
echo -e "${logoline18} Entorno Gráfico : ${environment}" >> final
echo -e "${logoline19}" >> final
echo -e "${logoline20}" >> final
echo -e "${logoline21}" >> final
echo -e "${logoline22}" >> final 
echo -e "${logoline23}" >> final
echo -e "${logoline24}" >> final
echo -e "${logoline25}" >> final
echo "" >> final 
echo "" >> final
echo "  Arcris Instalación fácil de ArchLinux - Donaciones en: www.patreon.com/codigocristo" >> final



cat final | yad  --geometry=775x455 --center --align="left" \
--text-info --window-icon="gtk-execute" --title="Información de Instalación" \
--button=" Cancelar!gtk-no:1" --button=" Instalar Arch Linux!gtk-ok:0" --buttons-layout="center" --borders="10"

if [ $? = "1" ] 
  	then killall yad
fi

sudo sh installsystem | yad  --geometry=690x455 --center --align="left" \
--text-info --tail --window-icon="gtk-execute" --title="Instalando Arch Linux - Arcris" \
--no-buttons --borders="10"



####### FINAL $$$$$$$$$$$$$$$$$ 
### ACA RECIBO MUCHAS DONACIONES Y DEJO MI EMPLEO
#################################################

yad  --geometry=400x10 --center  --selectable-labels --text-align="center" \
--timeout="20" --timeout-indicator="top" --skip-taskbar --text="<span color='white'><b>\nPorfavor Apoya este proyecto enviando tu donación: </b></span>\n\n<span color='#07BFFF'><b>paypal.me/codigocristo</b></span>\n\n<span color='white'><b>Con esa donación crearemos mejores programas</b></span>" --window-icon="gtk-dialog-info" --title="Arcris" \
--borders="10" --no-buttons

val=$(yad  --geometry=200x20 --center --align="left" \
--window-icon="gtk-dialog-question" --skip-taskbar --title="Arcris" \
--borders="10" --button="  Reiniciar computador !gtk-refresh:1" --button="  Salir de Arcris!gtk-quit:0" \
--buttons-layout="center")
ret=$?

[[ $ret -eq 1 ]] && \
umount -R /mnt && \
swapoff -a  && \
&& reboot

if [[ $ret -eq 0 ]]; then
    echo "Continuar"
    exit 0
fi


#sudo pacman -Sy --noconfirm  | yad --geometry=400x500 --text-info --tail  --text="\nInstalando\n"


#sudo pacman -Sy | yad --geometry=400x500 --listen --list --separator="" \
#--column="GRUB Menu Entry"