#! /bin/bash

partautoRoot1 () {
sgdisk --zap-all ${disco}
parted ${disco} mklabel gpt
sgdisk ${disco} -n=1:0:+100M -t=1:ef00
sgdisk ${disco} -n=2:0:0
fdisk -l ${disco} > partition
echo ""
cat partition
sleep 3
#
partition="$(cat partition | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"
rm partition
#
echo $partition | awk -F ' ' '{print $1}' >  boot-efi
echo $partition | awk -F ' ' '{print $2}' >  root-efi
#
clear
echo ""
echo "Formateando Particiones"
echo ""
mkfs.ext4 $(cat root-efi) 
mount $(cat root-efi) /mnt 
#
mkdir -p /mnt/efi 
mkfs.fat -F 32 $(cat boot-efi) 
mount $(cat boot-efi) /mnt/efi	
rm boot-efi && rm root-efi
		}