#! /bin/bash

partautoRoot1 () {

uefi=$( ls /sys/firmware/efi/ | grep -ic efivars )

	if [ $uefi == 1 ]; then
        
umount -R /mnt
swapoff -a

sgdisk --zap-all ${disco}
parted ${disco} mklabel gpt
sgdisk ${disco} -n=1:0:+150M -t=1:ef00
sgdisk ${disco} -n=2:0:0
fdisk -l ${disco} > partition
echo ""
cat partition
sleep 3
#
partition="$(cat partition | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"
rm partition
#
echo $partition | awk -F ' ' '{print $1}' >  boot-efi
echo $partition | awk -F ' ' '{print $2}' >  root-efi
#
clear
echo ""
echo "Formateando Particiones"
echo ""
mkfs.ext4 $(cat root-efi) 
mount $(cat root-efi) /mnt 
#
mkdir -p /mnt/efi 
mkfs.fat -F 32 $(cat boot-efi) 
mount $(cat boot-efi) /mnt/efi	
rm boot-efi && rm root-efi

		else

umount -R /mnt
swapoff -a

sgdisk --zap-all ${disco}
(echo o; echo n; echo p; echo 1; echo ""; echo +150M; echo n; echo p; echo 2; echo ""; echo "";  echo a; echo 1; echo w; echo q) | fdisk ${disco}
fdisk -l ${disco} > partition
echo ""
cat partition
sleep 3
#
partition="$(cat partition | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"
rm partition
#
echo $partition | awk -F ' ' '{print $1}' >  boot-boot
echo $partition | awk -F ' ' '{print $2}' >  root-boot
#
clear
echo ""
echo "Formateando Particiones"
echo ""
mkfs.ext4 $(cat root-boot) 
mount $(cat root-boot) /mnt 

mkdir -p /mnt/boot 
mkfs.ext4 $(cat boot-boot) 
mount $(cat boot-boot) /mnt/boot
rm boot-boot && rm root-boot

		fi



		}


partautoSwap1 () {

uefi=$( ls /sys/firmware/efi/ | grep -ic efivars )

	if [ $uefi == 1 ]; then

umount -R /mnt
swapoff -a

sgdisk --zap-all ${disco}
parted ${disco} mklabel gpt
sgdisk ${disco} -n=1:0:+150M -t=1:ef00
sgdisk ${disco} -n=2:0:+${swapauto}G -t=2:8200
sgdisk ${disco} -n=3:0:0
fdisk -l ${disco} > partition
echo ""
cat partition
sleep 3

partition="$(cat partition | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"
rm partition

echo $partition | awk -F ' ' '{print $1}' >  boot-efi
echo $partition | awk -F ' ' '{print $2}' >  swap-efi
echo $partition | awk -F ' ' '{print $3}' >  root-efi

mkfs.ext4 $(cat root-efi) 
mount $(cat root-efi) /mnt 

mkdir -p /mnt/efi 
mkfs.fat -F 32 $(cat boot-efi) 
mount $(cat boot-efi) /mnt/efi 

mkswap $(cat swap-efi) 
swapon $(cat swap-efi)
rm boot-efi && rm root-efi && rm swap-efi

	else


umount -R /mnt
swapoff -a

sgdisk --zap-all ${disco}
(echo o; echo n; echo p; echo 1; echo ""; echo +150M; echo n; echo p; echo 2; echo ""; echo +${swapauto}G; echo n; echo p; echo 3; echo ""; echo ""; echo t; echo 2; echo 82; echo a; echo 1; echo w; echo q) | fdisk ${disco}
fdisk -l ${disco} > partition
echo ""
cat partition
sleep 3
#
partition="$(cat partition | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"
rm partition
#
echo $partition | awk -F ' ' '{print $1}' >  boot-boot
echo $partition | awk -F ' ' '{print $2}' >  swap-boot
echo $partition | awk -F ' ' '{print $3}' >  root-boot
#
clear
echo ""
echo "Formateando Particiones"
echo ""
mkfs.ext4 $(cat root-boot) 
mount $(cat root-boot) /mnt 

mkdir -p /mnt/boot 
mkfs.ext4 $(cat boot-boot) 
mount $(cat boot-boot) /mnt/boot

mkswap $(cat swap-boot) 
swapon $(cat swap-boot)
rm boot-boot && rm root-boot && rm swap-boot


	fi
		}


partautoHome1 () {

uefi=$( ls /sys/firmware/efi/ | grep -ic efivars )

	if [ $uefi == 1 ]; then

umount -R /mnt
swapoff -a

sgdisk --zap-all ${disco}
parted ${disco} mklabel gpt
sgdisk ${disco} -n=1:0:+150M -t=1:ef00
sgdisk ${disco} -n=2:0:+${rootauto}G -t=2:8300
sgdisk ${disco} -n=3:0:0
fdisk -l ${disco} > partition
echo ""
cat partition
sleep 3

partition="$(cat partition | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"
rm partition

echo $partition | awk -F ' ' '{print $1}' >  boot-efi
echo $partition | awk -F ' ' '{print $2}' >  root-efi
echo $partition | awk -F ' ' '{print $3}' >  home-efi

mkfs.ext4 $(cat root-efi) 
mount $(cat root-efi) /mnt 

mkdir -p /mnt/home
mkfs.ext4 $(cat home-efi) 
mount $(cat home-efi) /mnt/home

mkdir -p /mnt/efi 
mkfs.fat -F 32 $(cat boot-efi) 
mount $(cat boot-efi) /mnt/efi 
rm boot-efi && rm root-efi && rm home-efi

else

umount -R /mnt
swapoff -a

sgdisk --zap-all ${disco}
(echo o; echo n; echo p; echo 1; echo ""; echo +150M; echo n; echo p; echo 2; echo ""; echo +${rootauto}G; echo n; echo p; echo 3; echo ""; echo ""; echo w; echo q) | fdisk ${disco}

fdisk -l ${disco} > partition
echo ""
cat partition
sleep 3
#
partition="$(cat partition | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"
rm partition
#
echo $partition | awk -F ' ' '{print $1}' >  boot-boot
echo $partition | awk -F ' ' '{print $2}' >  root-boot
echo $partition | awk -F ' ' '{print $3}' >  home-boot
#
clear
echo ""
echo "Formateando Particiones"
echo ""
mkfs.ext4 $(cat root-boot) 
mount $(cat root-boot) /mnt 

mkdir -p /mnt/boot 
mkfs.ext4 $(cat boot-boot) 
mount $(cat boot-boot) /mnt/boot

mkdir -p /mnt/home
mkfs.ext4 $(cat home-boot) 
mount $(cat home-boot) /mnt/home
rm boot-boot && rm root-boot && rm home-boot

	fi
		}



partautoHomeSwap1 () {


uefi=$( ls /sys/firmware/efi/ | grep -ic efivars )

	if [ $uefi == 1 ]; then

umount -R /mnt
swapoff -a

sgdisk --zap-all ${disco}
parted ${disco} mklabel gpt
sgdisk ${disco} -n=1:0:+150M -t=1:ef00
sgdisk ${disco} -n=2:0:+${swapauto}G -t=2:8200
sgdisk ${disco} -n=3:0:+${rootauto}G -t=3:8300
sgdisk ${disco} -n=4:0:0
sudo fdisk -l ${disco} > partition
echo ""
echo ""
cat partition
sleep 3


partition="$(cat partition | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"

echo $partition | awk -F ' ' '{print $1}' >  boot-efi
echo $partition | awk -F ' ' '{print $2}' >  swap-efi
echo $partition | awk -F ' ' '{print $3}' >  root-efi
echo $partition | awk -F ' ' '{print $4}' >  home-efi

mkfs.ext4 $(cat root-efi) 
mount $(cat root-efi) /mnt 

mkdir -p /mnt/efi 
mkfs.fat -F 32 $(cat boot-efi) 
mount $(cat boot-efi) /mnt/efi 

mkdir -p /mnt/home
mkfs.ext4 $(cat home-efi) 
mount $(cat home-efi) /mnt/home

mkswap $(cat swap-efi) 
swapon $(cat swap-efi)

rm partition
rm boot-efi && rm root-efi && rm home-efi && rm swap-efi

else


umount -R /mnt
swapoff -a

sgdisk --zap-all ${disco}
(echo o; echo n; echo p; echo 1; echo ""; echo +150M; echo n; echo p; echo 2; echo ""; echo +${swapauto}G; echo n; echo p; echo 3; echo ""; echo +${rootauto}G; echo n; echo p; echo 4; echo ""; echo ""; echo t; echo 2; echo 82; echo a; echo 1; echo w; echo q) | fdisk ${disco}
fdisk -l ${disco} > partition
echo ""
cat partition
sleep 3
#
partition="$(cat partition | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"
rm partition
#
echo $partition | awk -F ' ' '{print $1}' >  boot-boot
echo $partition | awk -F ' ' '{print $2}' >  swap-boot
echo $partition | awk -F ' ' '{print $3}' >  root-boot
echo $partition | awk -F ' ' '{print $4}' >  home-boot
#
clear
echo ""
echo "Formateando Particiones"
echo ""
mkfs.ext4 $(cat root-boot) 
mount $(cat root-boot) /mnt 

mkdir -p /mnt/boot 
mkfs.ext4 $(cat boot-boot) 
mount $(cat boot-boot) /mnt/boot

mkswap $(cat swap-boot) 
swapon $(cat swap-boot)

mkdir -p /mnt/home
mkfs.ext4 $(cat home-boot) 
mount $(cat home-boot) /mnt/home

rm boot-boot && rm root-boot && rm swap-boot && rm home-boot

	fi
		}



# echo $partition | sed '1q;d' >  boot-efi