#! /bin/bash

partautoRoot1 () {
umount -R /mnt

sgdisk --zap-all ${disco}
parted ${disco} mklabel gpt
sgdisk ${disco} -n=1:0:+150M -t=1:ef00
sgdisk ${disco} -n=2:0:0
fdisk -l ${disco} > partition
echo ""
cat partition
sleep 3
#
partition="$(cat partition | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"
rm partition
#
echo $partition | awk -F ' ' '{print $1}' >  boot-efi
echo $partition | awk -F ' ' '{print $2}' >  root-efi
#
clear
echo ""
echo "Formateando Particiones"
echo ""
mkfs.ext4 $(cat root-efi) 
mount $(cat root-efi) /mnt 
#
mkdir -p /mnt/efi 
mkfs.fat -F 32 $(cat boot-efi) 
mount $(cat boot-efi) /mnt/efi	
rm boot-efi && rm root-efi
		}


partautoSwap1 () {
umount -R /mnt
swapoff -a

sgdisk --zap-all ${disco}
parted ${disco} mklabel gpt
sgdisk ${disco} -n=1:0:+150M -t=1:ef00
sgdisk ${disco} -n=2:0:+${swapauto}G -t=2:8200
sgdisk ${disco} -n=3:0:0
fdisk -l ${disco} > partition
echo ""
cat partition
sleep 3

partition="$(cat partition | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"
rm partition

echo $partition | awk -F ' ' '{print $1}' >  boot-efi
echo $partition | awk -F ' ' '{print $2}' >  swap-efi
echo $partition | awk -F ' ' '{print $3}' >  root-efi

mkfs.ext4 $(cat root-efi) 
mount $(cat root-efi) /mnt 

mkdir -p /mnt/efi 
mkfs.fat -F 32 $(cat boot-efi) 
mount $(cat boot-efi) /mnt/efi 

mkswap $(cat swap-efi) 
swapon $(cat swap-efi)
rm boot-efi && rm root-efi && rm swap-efi
		}


partautoHome1 () {
umount -R /mnt
swapoff -a

sgdisk --zap-all ${disco}
parted ${disco} mklabel gpt
sgdisk ${disco} -n=1:0:+150M -t=1:ef00
sgdisk ${disco} -n=3:0:+${homeauto}G -t=2:8300
sgdisk ${disco} -n=2:0:0
fdisk -l ${disco} > partition
echo ""
cat partition
sleep 3

partition="$(cat partition | grep /dev/ | awk '{if (NR!=1) {print}}' | sed 's/*//g' | awk -F ' ' '{print $1}')"
rm partition

echo $partition | awk -F ' ' '{print $1}' >  boot-efi
echo $partition | awk -F ' ' '{print $2}' >  home-efi
echo $partition | awk -F ' ' '{print $3}' >  root-efi

mkfs.ext4 $(cat root-efi) 
mount $(cat root-efi) /mnt 

mkdir -p /mnt/home
mkfs.ext4 $(cat home-efi) 
mount $(cat home-efi) /mnt/home

mkdir -p /mnt/efi 
mkfs.fat -F 32 $(cat boot-efi) 
mount $(cat boot-efi) /mnt/efi 
rm boot-efi && rm root-efi && rm home-efi
		}





