#!/bin/bash


installkernel () {

case $kernel_select in

  linux-stable)

arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Sy alsi --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -Sy yay-bin --noconfirm --needed"

arch-chroot /mnt /bin/bash -c "pacman -S linux --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S linux-headers --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S linux-firmware --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S mkinitcpio --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S pacman-mirrorlist --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S cryptsetup --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S lvm2 --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S logrotate --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S nano --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S hddtemp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S unzip --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S zip --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dnsmasq --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ethtool --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ndisc6 --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S inetutils --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S wvdial --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S gptfdisk --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dhcp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dhcpcd --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dhclient --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ppp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S netctl --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S networkmanager --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S iwd --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S net-tools --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ifplugd --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dialog --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S neofetch --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S git --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S wget --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S lsb-release --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S accountsservice --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S bash-completion --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S less --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ntp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S usb_modeswitch --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S usbutils --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S which --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S mtools --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S exfat-utils --noconfirm --needed"

arch-chroot /mnt /bin/bash -c "systemctl enable dhcpcd NetworkManager"

  ;;

  linux-hardened)

arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Sy alsi --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -Sy yay-bin --noconfirm --needed"

arch-chroot /mnt /bin/bash -c "pacman -S linux-hardened --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S linux-hardened-headers --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S linux-firmware --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S mkinitcpio --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S pacman-mirrorlist --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S cryptsetup --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S lvm2 --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S logrotate --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S nano --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S hddtemp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S unzip --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S zip --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dnsmasq --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ethtool --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ndisc6 --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S inetutils --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S wvdial --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S gptfdisk --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dhcp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dhcpcd --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dhclient --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ppp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S netctl --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S networkmanager --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S iwd --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S net-tools --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ifplugd --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dialog --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S neofetch --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S git --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S wget --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S lsb-release --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S accountsservice --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S bash-completion --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S less --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ntp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S usb_modeswitch --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S usbctl --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S usbutils --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S which --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S mtools --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S exfat-utils --noconfirm --needed"

arch-chroot /mnt /bin/bash -c "systemctl enable dhcpcd NetworkManager"

  ;;

  linux-lts)

arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Sy alsi --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -Sy yay-bin --noconfirm --needed"

arch-chroot /mnt /bin/bash -c "pacman -S linux-lts --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S linux-lts-headers --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S linux-firmware --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S mkinitcpio --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S pacman-mirrorlist --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S cryptsetup --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S lvm2 --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S logrotate --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S nano --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S hddtemp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S unzip --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S zip --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dnsmasq --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ethtool --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ndisc6 --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S inetutils --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S wvdial --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S gptfdisk --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dhcp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dhcpcd --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dhclient --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ppp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S netctl --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S networkmanager --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S iwd --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S net-tools --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ifplugd --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dialog --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S neofetch --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S git --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S wget --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S lsb-release --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S accountsservice --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S bash-completion --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S less --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ntp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S usb_modeswitch --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S usbutils --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S which --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S mtools --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S exfat-utils --noconfirm --needed"

arch-chroot /mnt /bin/bash -c "systemctl enable dhcpcd NetworkManager"

  ;;

  linux-zen)

arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -Sy alsi --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -Sy yay-bin --noconfirm --needed"

arch-chroot /mnt /bin/bash -c "pacman -S linux-zen --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S linux-zen-headers --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S linux-firmware --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S mkinitcpio --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S pacman-mirrorlist --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S cryptsetup --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S lvm2 --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S logrotate --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S nano --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S hddtemp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S unzip --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S zip --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dnsmasq --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ethtool --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ndisc6 --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S inetutils --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S wvdial --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S gptfdisk --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dhcp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dhcpcd --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dhclient --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ppp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S netctl --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S networkmanager --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S iwd --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S net-tools --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ifplugd --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S dialog --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S neofetch --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S git --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S wget --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S lsb-release --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S accountsservice --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S bash-completion --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S less --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S ntp --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S usb_modeswitch --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S usbutils --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S which --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S mtools --noconfirm --needed"
arch-chroot /mnt /bin/bash -c "pacman -S exfat-utils --noconfirm --needed"

arch-chroot /mnt /bin/bash -c "systemctl enable dhcpcd NetworkManager"

  ;;

esac





}







installshell () {



case $shell_select in

  zsh)

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S zsh --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S zsh-completions --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S zsh-syntax-highlighting --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S zsh-autosuggestions --noeditmenu --noconfirm --needed"

  ;;

  bash)

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S bash --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S bash-completion --noeditmenu --noconfirm --needed"

  ;;

  dash)
	
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dash --noeditmenu --noconfirm --needed"

  ;;

  fish)
	
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S fish --noeditmenu --noconfirm --needed"

  ;;

  mksh)
	
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mksh --noeditmenu --noconfirm --needed"

  ;;


  tcsh)

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S tcsh --noeditmenu --noconfirm --needed"

  ;;

esac


echo ""

arch-chroot /mnt /bin/bash -c "chsh -s /bin/$shell_select"
arch-chroot /mnt /bin/bash -c "chsh -s /usr/bin/$shell_select $username"
arch-chroot /mnt /bin/bash -c "chsh -s /bin/$shell_select $username"


cp .dialogrc /mnt/root
chmod +x /mnt/root/.dialogrc
cp .dialogrc /mnt/home/$username/.dialogrc
chmod +x /mnt/home/$username/.dialogrc

mkdir /mnt/etc/pacman.d/hooks/
cp mirrorupgrade.hook /mnt/etc/pacman.d/hooks/mirrorupgrade.hook 
chmod +x /mnt/etc/pacman.d/hooks/mirrorupgrade.hook

cp zshrc /mnt/home/$username/.zshrc
arch-chroot /mnt /bin/bash -c "chown -hR $username:users /home/$username/.zshrc"
cp zshrc /mnt/root/.zshrc

cp .bashrc /mnt/home/$username/.bashrc
cp .bashrc-root /mnt/root/.bashrc
arch-chroot /mnt /bin/bash -c "chown -hR $username:users /home/$username/.bashrc"


}



installucode () {

echo -e ""
echo -e "\t\t\t| Instalando Ucode del Sistema |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""

if [ "$ucode_select" == "TRUE" ]; then
    
microcode=$(lspci -k | grep 'Host bridge: Intel')
lspci -k | grep 'Host bridge:'  > procesador
if [[ $microcode  = *Intel* || $microcode = *intel* || $microcode = *INTEL* ]]
then
clear    
echo ""
echo ""     
cat procesador
echo ""   
arch-chroot /mnt /bin/bash -c "pacman -S intel-ucode --noconfirm"

else
clear
echo ""
echo ""     
cat procesador
echo ""  
arch-chroot /mnt /bin/bash -c "pacman -S amd-ucode --noconfirm"
fi

rm procesador
fi

}



installtouchpad () {

echo -e ""
echo -e "\t\t| Instalando Driver Touchpad del Sistema |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""

if [ "$touchpad_select" == "TRUE" ]; then
    

arch-chroot /mnt /bin/bash -c "pacman -S xf86-input-synaptics --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S xf86-input-libinput --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinput --noconfirm"


fi

}