#!/bin/bash


installvideo () {



case $video in

  "Automático")
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-* 
# Instalación de drivers de video 
# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-* 
echo "" 
echo "Se estan instalando los drivers de video Automático" 
sleep 3 
case $(systemd-detect-virt) in 
	oracle)

		if [ "$kernel_select" == "linux-stable" ]; then
        
        arch-chroot /mnt /bin/bash -c "pacman -S virtualbox-guest-utils --noconfirm" 
		arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-vmware --noconfirm" 
		arch-chroot /mnt /bin/bash -c "pacman -S virtualbox-host-modules-arch --noconfirm" 
		arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
		arch-chroot /mnt /bin/bash -c "modprobe -a vboxdrv"
		arch-chroot /mnt /bin/bash -c "modprobe -a vboxguest vboxsf vboxvideo"
		arch-chroot /mnt /bin/bash -c "modprobe -a vboxnetadp vboxnetflt vboxnetadp"
		arch-chroot /mnt /bin/bash -c "VBoxClient-all"
		arch-chroot /mnt /bin/bash -c "systemctl enable vboxservice.service"
		arch-chroot /mnt /bin/bash -c "systemctl enable systemd-modules-load.service"

		else

		arch-chroot /mnt /bin/bash -c "pacman -S virtualbox-guest-utils --noconfirm" 
		arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-vmware --noconfirm" 
		arch-chroot /mnt /bin/bash -c "pacman -S virtualbox-host-dkms --noconfirm" 
		arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
		arch-chroot /mnt /bin/bash -c "modprobe -a vboxdrv"
		arch-chroot /mnt /bin/bash -c "modprobe -a vboxguest vboxsf vboxvideo"
		arch-chroot /mnt /bin/bash -c "modprobe -a vboxnetadp vboxnetflt vboxnetadp"
		arch-chroot /mnt /bin/bash -c "VBoxClient-all"
		arch-chroot /mnt /bin/bash -c "systemctl enable vboxservice.service"
		arch-chroot /mnt /bin/bash -c "systemctl enable systemd-modules-load.service"

		fi
	;; 
	vmware) 
		arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-vmware --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S xf86-input-vmmouse --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S open-vm-tools --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S net-tools --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S gtkmm --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
	;; 
	qemu) 
		arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S mesa-libgl --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-fbdev --noconfirm"
	;; 
	kvm) 
		arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S mesa-libgl --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-fbdev --noconfirm"
	;; 
	microsoft) 
		arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S mesa-libgl --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-fbdev --noconfirm"
	;; 
	xen) 
		arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S mesa-libgl --noconfirm"
		arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-fbdev --noconfirm" 
	;; 
	*) 
		if (lspci | grep VGA | grep "NVIDIA\|nVidia" &>/dev/null); then 

			arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-nouveau --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S lib32-mesa --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S mesa-vdpau --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libva-mesa-driver --noconfirm"

		elif (lspci | grep VGA | grep "Radeon R\|R2/R3/R4/R5" &>/dev/null); then 

			arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-amdgpu --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S lib32-mesa --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S vulkan-radeon --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S lib32-vulkan-radeon --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S mesa-vdpau --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libva-mesa-driver --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S lib32-mesa-vdpau --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S lib32-libva-mesa-driver --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libva-vdpau-driver --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libvdpau-va-gl --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libva-utils --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S vdpauinfo --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S opencl-mesa --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S clinfo --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S ocl-icd --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S lib32-ocl-icd --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S opencl-headers --noconfirm"

		elif (lspci | grep VGA | grep "ATI\|AMD/ATI" &>/dev/null); then 

			arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-ati --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S lib32-mesa --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S mesa-vdpau --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libva-mesa-driver --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S lib32-mesa-vdpau --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S lib32-libva-mesa-driver --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libva-vdpau-driver --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libvdpau-va-gl --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libva-utils --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S vdpauinfo --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S opencl-mesa --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S clinfo --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S ocl-icd --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S lib32-ocl-icd --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S opencl-headers --noconfirm"

		elif (lspci | grep VGA | grep "Intel" &>/dev/null); then 

			arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-intel --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S vulkan-intel --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S lib32-mesa --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S intel-media-driver --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libva-intel-driver --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libva-vdpau-driver --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libvdpau-va-gl --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S libva-utils --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S vdpauinfo --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S intel-compute-runtime --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S clinfo --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S ocl-icd --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S lib32-ocl-icd --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S opencl-headers --noconfirm"

		else

			arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-vesa --noconfirm"

	fi 
	;; 
esac 
sleep 2 

# -*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-* 
  ;;


  "Video_vesa_(Generic_All)")
	
	echo "" 
	echo "Se estan instalando los drivers de Video vesa (Generic All)" 
	arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-vesa --noconfirm"

  ;;

  "Intel_(Open_Source)")
	
	echo "" 
	echo "Se estan instalando los drivers de Video Intel (Open Source)" 
	arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-intel --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S vulkan-intel --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S lib32-mesa --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S intel-media-driver --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libva-intel-driver --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libva-vdpau-driver --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libvdpau-va-gl --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libva-utils --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S vdpauinfo --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S intel-compute-runtime --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S clinfo --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S ocl-icd --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S lib32-ocl-icd --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S opencl-headers --noconfirm"

  ;;


  "AMD/ATI_(Open_Source)")
	
	echo "" 
	echo "Se estan instalando los drivers de Video AMD/ATI (Open Source)" 
	arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-ati --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S lib32-mesa --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S mesa-vdpau --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libva-mesa-driver --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S lib32-mesa-vdpau --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S lib32-libva-mesa-driver --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libva-vdpau-driver --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libvdpau-va-gl --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libva-utils --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S vdpauinfo --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S opencl-mesa --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S clinfo --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S ocl-icd --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S lib32-ocl-icd --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S opencl-headers --noconfirm"

  ;;


  "AMD/Radeon_(Open_Source)")
	
	echo "" 
	echo "Se estan instalando los drivers de Video AMD/Radeon Open Source)" 
	arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-amdgpu --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S lib32-mesa --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S vulkan-radeon --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S lib32-vulkan-radeon --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S mesa-vdpau --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libva-mesa-driver --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S lib32-mesa-vdpau --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S lib32-libva-mesa-driver --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libva-vdpau-driver --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libvdpau-va-gl --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libva-utils --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S vdpauinfo --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S opencl-mesa --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S clinfo --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S ocl-icd --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S lib32-ocl-icd --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S opencl-headers --noconfirm"

  ;;


  "Nvidia_(Open_Source)")
	
	echo "" 
	echo "Se estan instalando los drivers de Video Nvidia (Open Source)" 
	arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-nouveau --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S mesa --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S lib32-mesa --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S mesa-vdpau --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S libva-mesa-driver --noconfirm"

  ;;

  "Nvidia_Privativo_470xx_(Linux_Stable)")
	
	echo "" 
	echo "Se estan instalando los drivers de Video Nvidia_Privativo_470xx_(Linux_Stable)" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-settings --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-nvidia-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libva-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S vdpauinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-nvidia --noconfirm --needed" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-opencl-nvidia --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffnvcodec-headers --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libxnvctrl --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S clinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-headers --noconfirm --needed"


  ;;


  "Nvidia_Privativo_390xx_(Linux_Stable)")
	
	echo "" 
	echo "Se estan instalando los drivers de Video Nvidia_Privativo_390xx_(Linux_Stable)" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-390xx --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-390xx-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-390xx-settings --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libxnvctrl-390xx --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-nvidia-390xx-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libva-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S vdpauinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-nvidia-390xx --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-opencl-nvidia-390xx --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S clinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-headers --noconfirm --needed"

  ;;


  "Nvidia_Privativo_470xx_(Linux_LTS)")
	
	echo "" 
	echo "Se estan instalando los drivers de Video Nvidia_Privativo_470xx_(Linux_LTS)" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-lts --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-settings --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-nvidia-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libva-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S vdpauinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-nvidia --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-opencl-nvidia --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffnvcodec-headers --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libxnvctrl --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S clinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-headers --noconfirm --needed"

  ;;


  "Nvidia_Privativo_390xx_(Linux_LTS)")
	
	echo "" 
	echo "Se estan instalando los drivers de Video Nvidia_Privativo_390xx_(Linux_LTS)" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-390xx-lts --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-390xx-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-nvidia-390xx-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libva-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S vdpauinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-nvidia-390xx --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-opencl-nvidia-390xx --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S clinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-headers --noconfirm --needed"

  ;;


  "Nvidia_Privativo_470xx_(Linux_Hardened_-_Zen)")
	
	echo "" 
	echo "Se estan instalando los drivers de Video Nvidia_Privativo_470xx_(Linux_Hardened_-_Zen)" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-dkms --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-nvidia-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libva-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S vdpauinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-nvidia --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-opencl-nvidia --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffnvcodec-headers --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libxnvctrl --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S clinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-headers --noconfirm --needed"

  ;;


  "Nvidia_Privativo_390xx_(Linux_Hardened_-_Zen)")
	
	echo "" 
	echo "Se estan instalando los drivers de Video vesa (Generic All)" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-390xx-dkms --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-390xx-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-nvidia-390xx-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libva-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S vdpauinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-nvidia-390xx --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-opencl-nvidia-390xx --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S clinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-headers --noconfirm --needed"

  ;;


  "Nvidia_Privativo_470xx_(Linux_Stable_+_Intel)")
	
	echo "" 
	echo "Se estan instalando los drivers de Video Nvidia_Privativo_470xx_(Linux_Stable_+_Intel)" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-settings --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nvidia-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-nvidia-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libva-utils --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xf86-video-intel --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S optimus-manager --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S bbswitch --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S optimus-manager-qt --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S vdpauinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-libvdpau --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-nvidia --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-opencl-nvidia --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffnvcodec-headers --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libxnvctrl --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S clinfo --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-ocl-icd --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opencl-headers --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "rmmod nvidia_uvm"
    arch-chroot /mnt /bin/bash -c "rmmod nvidia"

    arch-chroot /mnt /bin/bash -c "systemctl enable optimus-manager.service"
	arch-chroot /mnt /bin/bash -c "optimus-manager --switch auto"
	arch-chroot /mnt /bin/bash -c "optimus-manager --set-startup intel"
	arch-chroot /mnt /bin/bash -c "sudo -u $username optimus-manager --switch auto"
	arch-chroot /mnt /bin/bash -c "sudo -u $username optimus-manager --set-startup intel"

  ;;



esac

}





installenvironment () {

	case $environment in

  "tty")
	echo "" 
	echo "Se esta instalando el entorno TTY:" 
	echo "" 
	arch-chroot /mnt /bin/bash -c "pacman -Syu --noconfirm"

  ;;


  "Xfce4")
	echo "" 
	echo "Se esta instalando el entorno Xfce4:" 
	echo "" 
	arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xfce4 --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S xfce4-goodies --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter-settings --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S light-locker --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mugshot --noeditmenu --noconfirm --needed"
 
 	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nerd-fonts-hack --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

  ;;

  "Gnome_Completo")
	echo "" 
	echo "Se esta instalando el entorno Gnome:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome  --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-extra --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-shell --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-shell-extensions --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gdm --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S chrome-gnome-shell --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S webp-pixbuf-loader --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-tweaks --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nerd-fonts-hack --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S tumbler --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "systemctl enable gdm"

  ;;


  "Gnome_Minimalista")
	echo "" 
	echo "Se esta instalando el entorno Gnome:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-shell --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gdm --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-control-center --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-tweaks --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-terminal --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nerd-fonts-hack --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "systemctl enable gdm"

  ;;



  "KDE-Plasma_Completo")
	echo "" 
	echo "Se esta instalando el entorno KDE Plasma:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S plasma --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kde-applications --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S konsole --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S konqueror --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dolphin --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S discover --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S latte-dock --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S bluedevil --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kate --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kdialog --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S keditbookmarks --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kwrite --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S appmenu-gtk-module --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libdbusmenu-glib --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libdbusmenu-gtk3 --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libdbusmenu-gtk2 --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kfind --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S khelpcenter --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kscreen --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S powerdevil --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kdeconnect --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S kdegraphics-thumbnailers --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S sddm --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libxcb --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S qt5-virtualkeyboard --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nerd-fonts-hack --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "systemctl enable sddm"

  ;;


"KDE-Plasma_Minimalista")
	echo "" 
	echo "Se esta instalando el entorno KDE Plasma:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S plasma --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dolphin --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S konsole --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S discover --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S sddm --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libxcb --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S qt5-virtualkeyboard --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nerd-fonts-hack --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "systemctl enable sddm"

  ;;


"Deepin")
	echo "" 
	echo "Se esta instalando el entorno Deepin:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S deepin --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S deepin-extra --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm  --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter  --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lightdm-gtk-greeter-settings  --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S light-locker  --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S accountsservice --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nerd-fonts-hack --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbs --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ffmpegthumbnailer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freetype2 --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S poppler-glib --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S raw-thumbnailer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libgsf --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"

  ;;



  "i3wm")
	echo "" 
	echo "Se esta instalando el entorno i3wm:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S i3-gaps --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S i3blocks --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S i3lock --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S i3status --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rofi --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dmenu --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ly-git --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S thunar --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S polkit-gnome --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-keyring --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxappearance --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rxvt-unicode --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-themes-extra --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nerd-fonts-hack --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "systemctl enable ly"

  ;;


  "bspwm")
	echo "" 
	echo "Se esta instalando el entorno Bspwm:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "pacman -S xorg --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-apps --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-xinit --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xorg-twm --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S xterm --noconfirm"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S bspwm --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S sxhkd --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rofi --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dmenu --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S st --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ly-git --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S thunar --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S network-manager-applet --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S polkit-gnome --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-keyring --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lxappearance --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S rxvt-unicode --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnome-themes-extra --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gnu-free-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-hack --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-inconsolata --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-font-awesome --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S awesome-terminal-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S noto-fonts-emoji --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S nerd-fonts-hack --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "systemctl enable ly"

  ;;


esac

}








installaudio () {

	case $audio in

  "Pulse-Audio")
	echo "" 
	echo "Se esta instalando Pulse Audio:" 
	echo "" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pulseaudio --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pulseaudio-alsa --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pavucontrol --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pamixer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libcanberra-pulse --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libcanberra-gstreamer --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-alsa-plugins --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-libpulse --noeditmenu --noconfirm --needed"
        
  ;;


  "Alsa-Audio")
	echo "" 
	echo "Se esta instalando Alsa Audio:" 
	echo "" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S alsa-utils --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S alsa-plugins --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S alsa-oss --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S alsa-firmware --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pamixer --noeditmenu --noconfirm --needed"

  ;;

  "Jack-Audio")
	echo "" 
	echo "Se esta instalando Jack Audio:" 
	echo "" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S realtime-privileges --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S jack2 --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-jack2 --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S a2jmidid --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libffado --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S python-dbus --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S waf --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pro-audio --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lv2-plugins --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ladspa-plugins --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S dssi-plugins --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S vst-plugins --noeditmenu --noconfirm --needed"
     
  ;;


  "Pipewire-Audio")
	echo "" 
	echo "Se esta instalando Pipewire Audio:" 
	echo "" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pipewire --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pipewire-alsa --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pipewire-pulse --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pipewire-jack --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S gst-plugin-pipewire --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pipewire-media-session --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pipewire-zeroconf --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pipewire-jack-dropin --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-pipewire --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S lib32-pipewire-jack --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S helvum --noeditmenu --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username systemctl start --user pipewire-pulse.service"
	arch-chroot /mnt /bin/bash -c "systemctl start pipewire-pulse.service"
	arch-chroot /mnt /bin/bash -c "systemctl start pipewire.service"
	arch-chroot /mnt /bin/bash -c "systemctl start pipewire-media-session.service"
	arch-chroot /mnt /bin/bash -c "systemctl start pipewire.service"
	arch-chroot /mnt /bin/bash -c "systemctl start pipewire-media-session.service"

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S wireplumber --noeditmenu --noconfirm --needed"

	arch-chroot /mnt /bin/bash -c "systemctl disable pipewire-media-session"
	arch-chroot /mnt /bin/bash -c "systemctl start --user wireplumber.service"
	arch-chroot /mnt /bin/bash -c "systemctl start wireplumber.service"
	arch-chroot /mnt /bin/bash -c "pactl info"

  ;;



  "Ninguno")
	echo "" 

  ;;


esac

}






installaur () {

echo -e ""
echo -e "\t\t| Instalando AUR - Arch User Repository |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""

	case $aur in

  "yay-(Terminal)")
	echo "" 
	echo "Se esta instalando AUR Yay:" 
	echo "" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -Syu --noeditmenu --noconfirm --needed"

  ;;


  "paru-(Terminal)")
	echo "" 
	echo "Se esta instalando AUR Paru:" 
	echo "" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S paru-bin --noconfirm --needed"

  ;;

  "pamac-(Graphical)")
	echo "" 
	echo "Se esta instalando AUR Pamac Gráfico:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S pamac-aur --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libpamac-aur --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S archlinux-appstream-data-pamac --noconfirm --needed"

  ;;


  "Octopi-(Graphical)")
	echo "" 
	echo "Se esta instalando AUR Octopi Gráfico:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S octopi --noconfirm --needed"

  ;;


  "Ninguno")
	echo "" 
	echo "Se esta eliminando el asistente AUR:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "pacman -R yay-bin --noconfirm"


  ;;

esac

}





installwebs () {


	case $web in

  "Ninguno")

	echo ""

  ;;


  "Firefox")
	echo -e ""
	echo -e "\t\t| Instalando Navegador Web |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""
	echo "" 
	echo "Se esta instalando AUR Paru:" 
	echo "" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S firefox --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S firefox-i18n-es-mx --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S firefox-i18n-es-es --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S passff-host --noconfirm --needed"

  ;;

  "Chromium")
	echo -e ""
	echo -e "\t\t| Instalando Navegador Web |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""
	echo "" 
	echo "Se esta instalando AUR Pamac Gráfico:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S chromium --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S passff-host --noconfirm --needed"


  ;;


  "Brave")
	echo -e ""
	echo -e "\t\t| Instalando Navegador Web |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""
	echo "" 
	echo "Se esta instalando AUR Octopi Gráfico:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S brave-bin --noconfirm --needed"


  ;;


  "Google-Chrome")
	echo -e ""
	echo -e "\t\t| Instalando Navegador Web |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""
	echo "" 
	echo "Se esta eliminando el asistente AUR:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S google-chrome --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S passff-host --noconfirm --needed"


  ;;


  "Opera")
	echo -e ""
	echo -e "\t\t| Instalando Navegador Web |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""
	echo "" 
	echo "Se esta eliminando el asistente AUR:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S opera --noconfirm --needed"

  ;;


  "Vivaldi")
	echo -e ""
	echo -e "\t\t| Instalando Navegador Web |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""
	echo "" 
	echo "Se esta eliminando el asistente AUR:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S vivaldi --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S passff-host --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S vivaldi-ffmpeg-codecs --noconfirm --needed"

  ;;

esac

}










installofi () {

	case $ofimatica in

  "Ninguno")

	echo ""

  ;;


  "LibreOffice")
	echo -e ""
	echo -e "\t\t| Instalando Ofimatica |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""
	echo "" 
	echo "Se esta instalando Libre Office:" 
	echo "" 
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libreoffice-fresh --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S libreoffice-fresh-es --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hunspell --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hunspell-es_es --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hunspell-es_any --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hyphen --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hyphen-es --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mythes-es --noconfirm --needed"

  ;;

  "WPS-Office")
	echo -e ""
	echo -e "\t\t| Instalando Ofimatica |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""
	echo "" 
	echo "Se esta instalando WPS Office:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S wps-office --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S ttf-wps-fonts --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hunspell --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hunspell-es_es --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hunspell-es_any --noconfirm --needed"

  ;;


  "SoftMaker-Office")
	echo -e ""
	echo -e "\t\t| Instalando Ofimatica |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""
	echo "" 
	echo "Se esta instalando SoftMaker Office:" 
	echo "" 

	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S freeoffice --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hunspell --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hunspell-es_es --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hunspell-es_any --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hyphen --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S hyphen-es --noconfirm --needed"
	arch-chroot /mnt /bin/bash -c "sudo -u $username yay -S mythes-es --noconfirm --needed"

  ;;



esac

}




installwifi () {

	case $wifi in

  "Ninguno")

	echo ""

  ;;


  "Automático")
	echo -e ""
	echo -e "\t\t| Instalando Driver de Wifi |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""

		if [ "$kernel_select" == "linux-stable" ]; then
        
			broadcom=$(/bin/bash -c "lspci -k | grep 'Network controller: Broadcom' ")
			if [[ $broadcom  = *Broadcom* || $broadcom = *broadcom* || $broadcom = *BROADCOM* ]]
			then            
			arch-chroot /mnt /bin/bash -c "pacman -S broadcom-wl --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S wireless-regdb --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S wpa_supplicant --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S wireless_tools --noconfirm"
			arch-chroot /mnt /bin/bash -c 'modprobe wl' 
			arch-chroot /mnt /bin/bash -c 'rmmod b43'
			arch-chroot /mnt /bin/bash -c 'rmmod ssb' 
			echo Listo
			else  
			arch-chroot /mnt /bin/bash -c "pacman -S iw wireless_tools wpa_supplicant dialog wireless-regdb --noconfirm"
			fi

		else

			broadcom=$(arch-chroot /mnt /bin/bash -c "lspci -k | grep 'Network controller: Broadcom' ")
			if [[ $broadcom  = *Broadcom* || $broadcom = *broadcom* || $broadcom = *BROADCOM* ]]
			then      
			arch-chroot /mnt /bin/bash -c "pacman -S broadcom-wl-dkms --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S wireless-regdb --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S wpa_supplicant --noconfirm"
			arch-chroot /mnt /bin/bash -c "pacman -S wireless_tools --noconfirm"			
			arch-chroot /mnt /bin/bash -c 'modprobe wl' 
			arch-chroot /mnt /bin/bash -c 'rmmod b43' 
			arch-chroot /mnt /bin/bash -c 'rmmod ssb' 
			echo listo
			else
			arch-chroot /mnt /bin/bash -c "pacman -S iw wireless_tools wpa_supplicant dialog wireless-regdb --noconfirm"
			fi

		fi

  ;;

  "Broadcom-802.11-Linux-Stable")
	echo -e ""
	echo -e "\t\t| Instalando Driver de Wifi |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""

	arch-chroot /mnt /bin/bash -c "pacman -S broadcom-wl --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S wireless-regdb --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S wpa_supplicant --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S wireless_tools --noconfirm"
	arch-chroot /mnt /bin/bash -c 'modprobe wl' 
	arch-chroot /mnt /bin/bash -c 'rmmod b43'
	arch-chroot /mnt /bin/bash -c 'rmmod ssb' 


  ;;


  "Broadcom-802.11-Others-Kernels")
	echo -e ""
	echo -e "\t\t| Instalando Driver de Wifi |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""

	arch-chroot /mnt /bin/bash -c "pacman -S broadcom-wl-dkms --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S wireless-regdb --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S wpa_supplicant --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S wireless_tools --noconfirm"			
	arch-chroot /mnt /bin/bash -c 'modprobe wl' 
	arch-chroot /mnt /bin/bash -c 'rmmod b43' 
	arch-chroot /mnt /bin/bash -c 'rmmod ssb' 

  ;;



esac

}







installblue () {

	case $bluetooth in

  "Ninguno")

	echo ""

  ;;


  "bluetoothctl-(Terminal)")
	echo -e ""
	echo -e "\t\t| Instalando Driver de Bluetooth |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""

	arch-chroot /mnt /bin/bash -c "pacman -S bluez --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S bluez-utils --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S pulseaudio-bluetooth --noconfirm"
	arch-chroot /mnt /bin/bash -c "systemctl enable bluetooth.service"


  ;;

  "blueman-(Graphical)")
	echo -e ""
	echo -e "\t\t| Instalando Driver de Bluetooth |"
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
	echo -e ""

	arch-chroot /mnt /bin/bash -c "pacman -S bluez --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S bluez-utils --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S pulseaudio-bluetooth --noconfirm"
	arch-chroot /mnt /bin/bash -c "pacman -S blueman --noconfirm"
	arch-chroot /mnt /bin/bash -c "systemctl enable bluetooth.service"


  ;;




esac

}