#!/bin/bash

installgrub () {

######
#GRUB
######
uefi=$( ls /sys/firmware/efi/ | grep -ic efivars )

fdisk -l ${disco} > partitions

if [ $uefi == 1 ] && [ -d /sys/firmware/efi ]; then

echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t| SU SISTEMA ES UEFI |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
cat partitions | grep gpt 
arch-chroot /mnt /bin/bash -c "pacman -S grub efibootmgr os-prober --noconfirm"

echo ""
echo '>>> Su disco es GPT | UEFI es el sistema Moderno <<<'
cat partitions | grep gpt 
sleep 3
echo '' 
echo 'Instalando EFI System >> bootx64.efi' 
arch-chroot /mnt /bin/bash -c 'grub-install --target=x86_64-efi --efi-directory=/boot/efi --removable' 
echo '' 
echo 'Instalando UEFI System >> grubx64.efi' 
arch-chroot /mnt /bin/bash -c 'grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Arch'
######
sed -i '6iGRUB_CMDLINE_LINUX_DEFAULT="loglevel=3"' /mnt/etc/default/grub
sed -i '7d' /mnt/etc/default/grub
echo "GRUB_DISABLE_OS_PROBER=false" >>  /mnt/etc/default/grub
######
echo ''
arch-chroot /mnt /bin/bash -c "grub-mkconfig -o /boot/grub/grub.cfg"
echo '' 
echo 'ls -l /mnt/boot' 
ls -l /mnt/boot 
echo '' 
echo 'Lea bien que no tenga ningún error marcado' 
echo '> Confirme tener las IMG de linux para el arranque' 
echo '> Confirme tener la carpeta de GRUB para el arranque' 
rm partitions
sleep 3


else

echo "" 
echo "" 
echo -e ""
echo -e "\t\t\t|  SISTEMA BIOS LEGACY Y DISCO DOS/MBR  |"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' _
echo -e ""
cat partitions | grep dos 
arch-chroot /mnt /bin/bash -c "pacman -S grub os-prober --noconfirm"

echo "" 
echo '>>> Su disco es DOS MBR | BIOS Legacy es un sistema antiguo <<<' 
echo "" 
cat partitions | grep dos 
sleep 3
echo '' 
arch-chroot /mnt /bin/bash -c "grub-install --target=i386-pc ${disco}"
########
sed -i '6iGRUB_CMDLINE_LINUX_DEFAULT="loglevel=3"' /mnt/etc/default/grub
sed -i '7d' /mnt/etc/default/grub
echo "GRUB_DISABLE_OS_PROBER=false" >>  /mnt/etc/default/grub
########
echo '' 
arch-chroot /mnt /bin/bash -c "grub-mkconfig -o /boot/grub/grub.cfg"
echo '' 
echo 'ls -l /mnt/boot' 
ls -l /mnt/boot 
echo '' 
echo 'Lea bien que no tenga ningún error marcado' 
echo '> Confirme tener las IMG de linux para el arranque' 
echo '> Confirme tener la carpeta de GRUB para el arranque'
rm partitions
sleep 3

fi
# FIN GRUB

}
