#! /bin/bash

source bash/diskauto


##################################################
export -f partautoRoot1

partautoRoot () {

partautoRoot1 | yad --progress --title="Discos" --width=430 --height=100 \
--text="\tFormateando y Montando discos, Porfavor espere ..." \
--image="drive-harddisk" --window-icon="drive-harddisk" \
--pulsate --buttons-layout="center" --borders="10" \
--auto-close --hide-text \
--button="Cancelar (No recomendado):0"

lsblk ${disco} | yad --center --geometry="100x300" --window-icon="drive-harddisk"  \
--image="drive-harddisk"  --align="center" --text-info \
--title "Disco Seleccionado" --text="\n\t\tParticiones Montadas\n" \
--button="Confirmar:0" --buttons-layout="center" --borders="10"
		}


##################################################
export -f partautoSwap1

partautoSwap () {

swapauto=$(yad --scale --text "  Define el tamaño en GiB para SWAP" --value="1" --min-value="1" --max-value="20" \
--inc-buttons --mark=[GiB]:10 \
--button="Confirmar:0" --buttons-layout="center" --borders="20" \
--image="drive-harddisk" --window-icon="drive-harddisk" \
--title="Partición Swap" --width=330)

partautoSwap1 | yad --progress --title="Discos" --width=430 --height=100 \
--text="\tFormateando y Montando discos, Porfavor espere ..." \
--image="drive-harddisk" --window-icon="drive-harddisk" \
--pulsate --buttons-layout="center" --borders="10" \
--auto-close --hide-text \
--button="Cancelar (No recomendado):0"

lsblk ${disco} | yad --center --geometry="100x300" --window-icon="drive-harddisk"  \
--image="drive-harddisk"  --align="center" --text-info \
--title "Disco Seleccionado" --text="\n\t\tParticiones Montadas\n" \
--button="Confirmar:0" --buttons-layout="center" --borders="10"

}

##################################################
export -f partautoHome1

partautoHome () {

maxvalue=$(sudo fdisk -l ${disco} | grep "bytes," | awk '{print $5}' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' )

let maxvalue=$maxvalue-30

homeauto=$(yad --scale --text "  Define el tamaño en GiB para Home" --value="10" --step="10" --min-value="1" --max-value=${maxvalue} \
--inc-buttons --mark=[GiB]:10 \
--button="Confirmar:0" --buttons-layout="center" --borders="20" \
--image="drive-harddisk" --window-icon="drive-harddisk" \
--title="Partición Home" --width=330)

partautoHome1 | yad --progress --title="Discos" --width=430 --height=100 \
--text="\tFormateando y Montando discos, Porfavor espere ..." \
--image="drive-harddisk" --window-icon="drive-harddisk" \
--pulsate --buttons-layout="center" --borders="10" \
--auto-close --hide-text \
--button="Cancelar (No recomendado):0"

lsblk ${disco} | yad --center --geometry="100x300" --window-icon="drive-harddisk"  \
--image="drive-harddisk"  --align="center" --text-info \
--title "Disco Seleccionado" --text="\n\t\tParticiones Montadas\n" \
--button="Confirmar:0" --buttons-layout="center" --borders="10"

}


##################################################
export -f partautoHomeSwap1

partautoHomeSwap () {

swapauto=$(yad --scale --text "  Define el tamaño en GiB para SWAP" --value="1" --min-value="1" --max-value="8" \
--inc-buttons --mark=[GiB]:4 \
--button="Confirmar:0" --buttons-layout="center" --borders="20" \
--image="drive-harddisk" --window-icon="drive-harddisk" \
--title="Partición Swap" --width=330)

maxvalue=$(sudo fdisk -l ${disco} | grep "bytes," | awk '{print $5}' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' | sed -e's/.$//' )

let maxvalue=$maxvalue-20

rootauto=$(yad --scale --text "  Define el tamaño en GiB para Root" --value="20" --min-value="20" --max-value=${maxvalue} \
--inc-buttons --mark=[GiB]:25 \
--button="Confirmar:0" --buttons-layout="center" --borders="20" \
--image="drive-harddisk" --window-icon="drive-harddisk" \
--title="Partición Root" --width=330)

partautoHomeSwap1 | yad --progress --title="Discos" --width=430 --height=100 \
--text="\tFormateando y Montando discos, Porfavor espere ..." \
--image="drive-harddisk" --window-icon="drive-harddisk" \
--pulsate --buttons-layout="center" --borders="10" \
--auto-close --hide-text \
--button="Cancelar (No recomendado):0"

lsblk ${disco} | yad --center --geometry="100x300" --window-icon="drive-harddisk"  \
--image="drive-harddisk"  --align="center" --text-info \
--title "Disco Seleccionado" --text="\n\t\tParticiones Montadas\n" \
--button="Confirmar:0" --buttons-layout="center" --borders="10"

}






partauto () {
OUT=$(yad --skip-taskbar --on-top  --center --window-icon="drive-harddisk" \
--image="drive-harddisk" --text="Selecciona tu preferencia de configurar tu disco"  --title "Tipo de particionado"  \
--width="400" --height="250"  --list --radiolist --columns="3" \
--column "   Elección   " --column "   Tipo de particionado   " \
--column "   Commando":HD  \
--print-column="2" --print-column="3" --buttons-layout="center" --separator=" " --button="Seleccionar":2 \
True  "Solo Root ( EXT4 )" 'partautoRoot' \
False "Solo Root + Swap ( EXT4 )" 'partautoSwap' \
False "Solo Root + Home ( EXT4 )" 'partautoHome' \
False "Solo Root + Home + Swap ( EXT4 )" 'partautoHomeSwap')

if [ $? = "1" ]
  	then exit
fi

export -f partauto
export -f partautoRoot
export -f partautoSwap
export -f partautoHome
export -f partautoHomeSwap

lsblk -lno NAME,TYPE,SIZE | grep 'disk' | awk '{if (NR!=0) {print}}' | sed '/sr/d' | sed '/fd/d' | awk '{print "/dev/" $1 " "  $3}' | sort -iu | sed "$d"  > devices
sed -i ':a;N;$!ba;s/\n/ !/g' devices
sed -i "$d" devices

devices=$(awk '{print $0 " " }' devices )

disk=$(yad --skip-taskbar --center --geometry=400x100 --window-icon=drive-harddisk \
--button="Seleccionar:0" --buttons-layout="center" --borders="10" \
--title "Selecciona tu Disco Duro" --form \
--field="Selección de Disco: :CB" "$devices")

disco=$(echo $disk | awk '{print $1}')

echo $disco

$OUT

}


partmanual () {

zenity --warning --width="250" --height="50"  --text "\nMuy pronto\n"

}


partcifrado () {

zenity --warning --width="250" --height="50"  --text "\nMuy pronto\n"

}


partwindows () {

zenity --warning --width="250" --height="50"  --text "\nMuy pronto\n"

}


#sudo fdisk -l | grep /dev/ | grep ":" | awk '{if (NR=1) {print  $2, $3, $4}}' | sed -e 's/.$//' > disk.txt
#listdevice=$()








#partautoSwap () {
#yad --text-align=center --separator=" " --text="\nTodos los datos ingresados son en GiB \n" \
#--form --field="Partición Root : :RO" " GiB Restantes" \
#--field="Partición Swap : :NUM" "0\!1..20\!1"  > swapdisk

#varSwapdisk=$(awk '{print $3 }' swapdisk )
#rm swapdisk
#echo ${varSwapdisk}GB
#}

#partautoHome () {
#yad --text-align=center --separator=" " --text="\nTodos los datos ingresados son en GiB \n" \
#--form --field="Partición Root : :RO" " GiB Restantes" \
#--field="Partición Swap : :NUM" "0\!1..20\!1"  > homedisk
#
#varHomedisk=$(awk '{print $3 }' homedisk )
#rm homedisk
#echo ${varHomedisk}GB
#}

#partautoHomeSwap () {
#yad --text-align=center --separator=" " --text="\nTodos los datos ingresados son en GiB \n" \
#--form --field="Partición Root : :RO" " GiB Restantes" \
#--field="Partición Home : :NUM" "0\!10..700\!10" \
#--field="Partición Swap : :NUM" "0\!1..20\!1"  > homeswapdisk
#
#varSwapdisk=$(awk '{print $3 }' homeswapdisk )
#varHomedisk=$(awk '{print $4 }' homeswapdisk )
#rm homeswapdisk
#echo ${varSwapdisk}GB
#echo ${varHomedisk}GB
#}
