#! /bin/bash


desktop () {

DE=$(echo "Xfce4,Gnome_Completo,Gnome_Minimalista,KDE-Plasma_Completo,KDE-Plasma_Minimalista,Deepin,MATE")

yad --align=left --form  --separator=" " --item-separator="," \
--skip-taskbar --on-top  --center --window-icon="gtk-execute" --title "Entorno de escritorio" \
--image="gtk-about" --text="Un entorno de escritorio proporciona una completa interfaz gráfica de usuario" \
--button="Confirmar:0" --buttons-layout="center" --borders="10" \
--field="Desktop Environment (DE) : :CB" "${DE}" 

}

winmanager () {

WM=$(echo "i3wm,bspwm")

yad --align=left --form  --separator=" " --item-separator="," \
--skip-taskbar --on-top  --center --window-icon="gtk-execute" --title "Entorno de escritorio" \
--image="gtk-about" --text="Un gestor de ventanas proporciona al usuario una interfaz gráfica minimalista" \
--button="Confirmar:0" --buttons-layout="center" --borders="10" \
--field="Window Manager (WM) : :CB" "${WM}" 

}

deorwm () {
deorwm1=$(yad --skip-taskbar --on-top  --center --window-icon="gtk-execute" \
--image="gtk-about" --text="Selecciona tu Entorno para tu sistema Arch Linux"  --title "Entorno de escritorio"  \
--width="400" --height="210"  --list --radiolist --columns="3" \
--column "   Elección   " --column "   Entorno de escritorio   " \
--column "   Commando":HD  \
--print-column="2" --print-column="3" --buttons-layout="center" --separator=" " --button="Seleccionar":2 \
True "(TTY) Getty - Terminal Virtual" 'echo tty' \
False "(DE)  -  Desktop Environment" 'desktop' \
False "(WM) - Window Manager" 'winmanager' )

if [ $? = "1" ]
  	then exit
fi

export -f deorwm
export -f desktop
export -f winmanager

$deorwm1

}
