#! /bin/bash


yad --text-align=center --separator=" " --text="\nTodos los datos ingresados son en GiB \n" \
--form --field="Partición Root : :RO" " GiB Restantes" \
--field="Partición Home : :NUM" "0\!10..700\!10" \
--field="Partición Swap : :NUM" "0\!1..20\!1"  > swapdisk

varSwapdisk=$(awk '{print $3 }' swapdisk )
varHomedisk=$(awk '{print $4 }' swapdisk )
rm swapdisk
echo ${varSwapdisk}GB
echo ${varHomedisk}GB
