#! /bin/bash

yad --center --width=400 --window-icon="distributor-logo-archlinux" \
--image="distributor-logo-archlinux" --title="Arcris Install" \
--text="\t<b><span size='large' color='white'>Esta ISO es completamente ArchLinux \n\tIncluye un instalador gráfico de Arcris</span></b>" \
--undecorated --spaces --borders="25" --fixed \
--buttons-layout="center" --button=Instalar:1 --button=Cerrar:0

if [ $? = "1" ] 
  	then zenity --warning --width="250" --height="50"  --text "\nMuy pronto\n"
fi




